DATABASE_CONFIG={
                "Catalog":{
                    "name":"postgres",
                    "user":"postgres",
                    "password":"evoke@1234",
                    "host":"localhost",
                    "port":"5432"
                }
            }